apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: home-lan-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.60.201-192.168.60.254
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: home-lan-adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - home-lan-pool