apiVersion: vmoperator.vmware.com/v1alpha2
kind: VirtualMachine
metadata:
  name: vce-vm
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: guaranteed-small
  imageName: 192.168.60.85:9000/edge-VC_VMDK-x86_64-5.4.0.0-99130387-R5400-20231230-GA-134893-3c6e4f5c0f-updatable-ext4.ova
  powerState: poweredOn
  network.interfaces:
  - name: "GE1"
    network: "Dummy Network"
  - name: "GE2"
    network: "Dummy Network"
  - name: "GE3"
    network: "VM Network"
  vmMetadata:
    configMapName: vce-ovfprops
    transport: OvfEnv
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: vce-ovfprops
    namespace: default
data:
  password: "passw0rd"
  velocloud.vce.activation_code: "DGXU-R28P-XZ2L-4C5Z"
  velocloud.vce.vco: "vco12-usvi1.velocloud.net"
  velocloud.vce.vco_ignore_cert_errors: "true"