apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: vce-vm
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: guaranteed-small
  imageName: 192.168.60.85:9000/edge-5.2.0.2-bios-with-disk.ova
  powerState: poweredOn
  networkInterfaces:
  - networkName: "VCE LAN"
  - networkName: "Dummy Network"
  - networkName: "VM Network"
  - networkName: "Dummy Network"
  - networkName: "Dummy Network"
  - networkName: "Dummy Network"
  vmMetadata:
    configMapName: updated-vce-props
    transport: CloudInit
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: updated-vce-props
  namespace: default
data:
  user-data: |
    #cloud-config
    password: passw0rd
    chpasswd: { expire: False }
    ssh_pwauth: True
    velocloud:
      vce:
        vco: vco12-usvi1.velocloud.net
        activation_code: 3GVE-7KA2-X5J3-AVEN
        vco_ignore_cert_errors: true
