apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: vce-vm
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: guaranteed-small
  imageName: 192.168.60.85:9000/edge-5.2.0.2-002.ova
  powerState: poweredOn
  networkInterfaces:
  - networkName: "VCE LAN"
  - networkName: "Dummy Network"
  - networkName: "VM Network"
  - networkName: "Dummy Network"
  - networkName: "Dummy Network"
  - networkName: "Dummy Network"
  vmMetadata:
    configMapName: updated-vce-props
    transport: OvfEnv
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: updated-vce-props
  namespace: default
data:
  user-data: "I2Nsb3VkLWNvbmZpZwpwYXNzd29yZDogcGFzc3cwcmQKY2hwYXNzd2Q6IHsgZXhwaXJlOiBGYWxzZSB9CnNzaF9wd2F1dGg6IFRydWUKdmVsb2Nsb3VkOgogIHZjZToKICAgIHZjbzogdmNvMTItdXN2aTEudmVsb2Nsb3VkLm5ldAogICAgYWN0aXZhdGlvbl9jb2RlOiAzR1ZFLTdLQTItWDVKMy1BVkVOCiAgICB2Y29faWdub3JlX2NlcnRfZXJyb3JzOiB0cnVl"