kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vsphere-standard
provisioner: kubernetes.io/vsphere-volume 
parameters:
    diskformat: thin 
    datastore: "datastore1" 
reclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-init-pvc-a
  namespace: default
spec:
  storageClassName: vsphere-standard
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 10Gi
# todo: 
# - mount secrets for VCO
# - make a container image to generate ISO in PVC
---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: vce-vm
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: guaranteed-small
  imageName: 192.168.60.85:9000/VeloCloud-EdgeRooted.ova
  powerState: poweredOn
  networkInterfaces:
  - networkName: "VCE LAN"
  - networkName: "Dummy Network"
  - networkName: "VM Network"
  - networkName: "Dummy Network"
  - networkName: "Dummy Network"
  - networkName: "Dummy Network"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vce-prop
  namespace: default
data:
  instance-id: id-ovf
  user-data: |
    #cloud-config
    chpasswd: { expire: False }
    ssh_pwauth: True
    velocloud:
      vce:
        vco: vco12-usvi1.velocloud.net
        activation_code: 3GVE-7KA2-X5J3-AVEN
        vco_ignore_cert_errors: true
  hostname: new-vce