apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: new-vce
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: best-effort-ec-small
  imageName: 192.168.60.85:9000/edge-VC_VMDK-x86_64-5.4.0.0-99130387-R5400-20231230-GA-134893-3c6e4f5c0f-updatable-ext4.ova
  powerState: poweredOn
  networkInterfaces:
  - networkName: "Dummy Network"
    ethernetCardType: "vmxnet3"
  - networkName: "Dummy Network"
    ethernetCardType: "vmxnet3"
  - networkName: "VM Network"
    ethernetCardType: "vmxnet3"
  vmMetadata:
    configMapName: user-data-vce
    transport: CloudInit
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: user-data-vce
    namespace: default
data:
  user-data: |
    #cloud-config
    password: passw0rd 
    chpasswd: { expire: False }
    ssh_pwauth: True
    velocloud:
      vce:
        vco: vco12-usvi1.velocloud.net
        activation_code: DGXU-R28P-XZ2L-4C5Z
        vco_ignore_cert_errors: true
