apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: vce-vm
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
    vmoperator.vmware.com/cloudinit-type: cloudinitprep
spec:
  className: guaranteed-small
  imageName: 192.168.60.85:9000/edge-VC_VMDK-x86_64-5.2.0.2-10328-R5202-20231107-GA-125647-b452968bf3-updatable-ext4.ova
  powerState: poweredOn
  networkInterfaces:
  - networkName: "VCE LAN"
  - networkName: "Dummy Network"
  - networkName: "VM Network"
  - networkName: "Dummy Network"
  - networkName: "Dummy Network"
  - networkName: "Dummy Network"
  vmMetadata:
    configMapName: vce-props
    transport: CloudInit
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vce-props
  namespace: default
data:
  user-data: I2Nsb3VkLWNvbmZpZwpwYXNzd29yZDogcGFzc3cwcmQKY2hwYXNzd2Q6IHsgZXhwaXJlOiBGYWxzZSB9CnNzaF9wd2F1dGg6IFRydWUKdmVsb2Nsb3VkOgogIHZjZToKICAgIHZjbzogdmNvMTItdXN2aTEudmVsb2Nsb3VkLm5ldAogICAgYWN0aXZhdGlvbl9jb2RlOiAzR1ZFLTdLQTItWDVKMy1BVkVOCiAgICB2Y29faWdub3JlX2NlcnRfZXJyb3JzOiB0cnVl
