apiVersion: v1
kind: Namespace
metadata:
  name: websrv
  labels:
    name: websrv
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: websrv
data:
  index.html: |
    <html>
    <h1>Hello world!</h1>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-1
  namespace: websrv
spec:
  selector:
    matchLabels:
      app: nginx-hello-keswick
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-hello-keswick
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: nginx-index-file
      volumes:
        - name: nginx-index-file
          configMap:
            name: index-html-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: websrv-service
  namespace: websrv
spec:
  selector:
    app: nginx-hello-keswick
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: websrv-ing
  namespace: websrv
spec:
  rules:
  - host: websrv.192.168.60.210.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80