apiVersion: v1
kind: Namespace
metadata:
  name: websrv
  labels:
    name: websrv
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: websrv-local-storage
  namespace: websrv
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 100Mi
  storageClassName: "websrv-local-storage"
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: websrv-pvc
  namespace: websrv
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "websrv-local-storage"
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: websrv
data:
  index.html: |
    <html>
    <h1>Hello world!</h1>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-1
  namespace: websrv
spec:
  selector:
    matchLabels:
      app: nginx-hello-keswick
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-hello-keswick
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: nginx-index-file
          - mountPath: /test-mount
            name: pvc-mount
      volumes:
        - name: nginx-index-file
          configMap:
            name: index-html-configmap
        - name: pvc-mount
          persistentVolumeClaim:
            claimName: websrv-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: websrv
spec:
  selector:
    app: nginx-hello-keswick
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80